development:
  cloud_name: "beepbeepbeep"
  api_key: "452867746377847"
  api_secret: "jLlvbcp372hzeqPgsnw0OzJZurI"

production:
  cloud_name: "beepbeepbeep"
  api_key: "452867746377847"
  api_secret: "jLlvbcp372hzeqPgsnw0OzJZurI"